import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers'
// import { Worker } from '@react-pdf-viewer/core';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Productivity App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark w-screen h-screen overflow-hidden'>
      <body className={inter.className}><Providers>{children}</Providers></body>
    </html>
  )
}
